[package]
name = "main"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"


[dependencies]
elliptic-curve = "0.8"
sha2 = "0.9"
hex = "0.4"
secp256k1 = "0.16"
rand_core = { version = "0.5", features = ["getrandom"] }
ripemd = "0.1.3"